apiVersion: v1
kind: Secret
metadata:
  name: lil-poker-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  db-password: {{ .Values.postgres.password | quote }}
  cookie-secret: {{ .Values.auth.cookieSecret | quote }}
